### ISSUE TITLE
Strange behavior in Windows.

### ISSUE THREAD

**Issue by juanmard** [davidthings/tinyfpga_bx_usbserial#10] opened 2020-04-14 12:00 UTC
I am testing with a _TinyFPGA-BX_ and I get strange behavior regarding the original bootloader.
In the current configuration I can access the bootloader (COM6). It reacts correctly by sending you byte (0x00) and loads the user _bitstream_.
In device manager everything is correct (in Spanish... :-)).

![imagen](https://user-images.githubusercontent.com/17770252/79221589-61201080-7e56-11ea-817c-dcb2a462b1bd.png)

Loading the new "tinyfpga_bx_usbserial" stops accessing the port and _Windows 10_ reacts with a warning (also happens with the "hello_world" of @nalzok) giving an error 0x0A.

![imagen](https://user-images.githubusercontent.com/17770252/79222219-734e7e80-7e57-11ea-98d6-aa696579e62f.png)

I have tested it on a GNU/Linux distribution (Debian) and everything works perfectly however.
I suppose it is because of the CDC-ACM driver, but I don't understand what difference there is so that with the _bootloader_ it works and with this other _bitstream_ not. Any clues?

**Comment by nevercast** [comment] 2020-06-18 14:07
I believe I've resolved it, see chain here: https://twitter.com/NvrCast/status/1273614583211520004
and solution posted here: https://discourse.tinyfpga.com/t/usb-communication/613/65

The issue is that when wLength exceeds 8 bits, it wraps over and usbserial returns less bytes than it should 

https://github.com/davidthings/tinyfpga_bx_usbserial/blob/master/usb/usb_serial_ctrl_ep.v#L106-L108

This can happen because Windows (WHY!?) requests a very large Descriptor size, 265 bytes exactly. 
![image](https://user-images.githubusercontent.com/834342/85030470-98ea6200-b1d1-11ea-98d1-ca1591130e20.png)

**Comment by nevercast** [comment] 2020-06-19 01:12
A fix for this has been merged, are you able to check if the problem is resolved for you @juanmard ?

**Comment by juanmard** [comment] 2020-06-19 18:16
Yeeeessss!
Now it's ok!

![imagen](https://user-images.githubusercontent.com/17770252/85167692-83c11200-b269-11ea-82e8-2c0fee1538ff.png)

No error and example "hello_world" running... Thanks! ;)

**Comment by nevercast** [comment] 2020-06-20 00:02
Fantastic! Glad to see this is fixed for you!

**Closed as completed** 2020-06-22 15:56 UTC
